create table animalNames (
	id INT,
	name VARCHAR(50)
);
insert into animalNames (id, name) values (1, 'African elephant');
insert into animalNames (id, name) values (2, 'Northern phalarope');
insert into animalNames (id, name) values (3, 'Sloth, two-toed tree');
insert into animalNames (id, name) values (4, 'Blue-tongued lizard');
insert into animalNames (id, name) values (5, 'Goanna lizard');
insert into animalNames (id, name) values (6, 'Long-finned pilot whale');
insert into animalNames (id, name) values (7, 'Long-tailed spotted cat');
insert into animalNames (id, name) values (8, 'Frog (unidentified)');
insert into animalNames (id, name) values (9, 'Brush-tailed rat kangaroo');
insert into animalNames (id, name) values (10, 'Rhea, greater');
insert into animalNames (id, name) values (11, 'North American red fox');
insert into animalNames (id, name) values (12, 'Bee-eater, carmine');
insert into animalNames (id, name) values (13, 'Galapagos dove');
insert into animalNames (id, name) values (14, 'Woodpecker, red-headed');
insert into animalNames (id, name) values (15, 'Egret, cattle');
insert into animalNames (id, name) values (16, 'Blackbird, red-winged');
insert into animalNames (id, name) values (17, 'American alligator');
insert into animalNames (id, name) values (18, 'Darwin ground finch (unidentified)');
insert into animalNames (id, name) values (19, 'Grison');
insert into animalNames (id, name) values (20, 'Palm squirrel');
insert into animalNames (id, name) values (21, 'Grey phalarope');
insert into animalNames (id, name) values (22, 'Porcupine, african');
insert into animalNames (id, name) values (23, 'Steenbok');
insert into animalNames (id, name) values (24, 'Common mynah');
insert into animalNames (id, name) values (25, 'Partridge, coqui');
insert into animalNames (id, name) values (26, 'Steenbok');
insert into animalNames (id, name) values (27, 'Deer, mule');
insert into animalNames (id, name) values (28, 'Southern boubou');
insert into animalNames (id, name) values (29, 'Swan, trumpeter');
insert into animalNames (id, name) values (30, 'Squirrel, malabar');
insert into animalNames (id, name) values (31, 'European shelduck');
insert into animalNames (id, name) values (32, 'Green-winged macaw');
insert into animalNames (id, name) values (33, 'Red-necked phalarope');
insert into animalNames (id, name) values (34, 'Red-winged blackbird');
insert into animalNames (id, name) values (35, 'Alpaca');
insert into animalNames (id, name) values (36, 'Hornbill, leadbeateri''s ground');
insert into animalNames (id, name) values (37, 'European spoonbill');
insert into animalNames (id, name) values (38, 'Golden eagle');
insert into animalNames (id, name) values (39, 'Mountain duck');
insert into animalNames (id, name) values (40, 'Smith''s bush squirrel');
insert into animalNames (id, name) values (41, 'Fox, north american red');
insert into animalNames (id, name) values (42, 'Shelduck, common');
insert into animalNames (id, name) values (43, 'Stanley crane');
insert into animalNames (id, name) values (44, 'Bettong, brush-tailed');
insert into animalNames (id, name) values (45, 'Vulture, king');
insert into animalNames (id, name) values (46, 'Iguana, common green');
insert into animalNames (id, name) values (47, 'Gazelle, thomson''s');
insert into animalNames (id, name) values (48, 'Otter, oriental short-clawed');
insert into animalNames (id, name) values (49, 'Dusky rattlesnake');
insert into animalNames (id, name) values (50, 'Macaw, red and blue');
insert into animalNames (id, name) values (51, 'Ass, asiatic wild');
insert into animalNames (id, name) values (52, 'Ring-tailed coatimundi');
insert into animalNames (id, name) values (53, 'Galapagos dove');
insert into animalNames (id, name) values (54, 'Blesbok');
insert into animalNames (id, name) values (55, 'Mountain lion');
insert into animalNames (id, name) values (56, 'Common dolphin');
insert into animalNames (id, name) values (57, 'Gecko, barking');
insert into animalNames (id, name) values (58, 'Possum, golden brush-tailed');
insert into animalNames (id, name) values (59, 'Springbuck');
insert into animalNames (id, name) values (60, 'Boubou, southern');
insert into animalNames (id, name) values (61, 'Lechwe, kafue flats');
insert into animalNames (id, name) values (62, 'Golden brush-tailed possum');
insert into animalNames (id, name) values (63, 'Crane, stanley');
insert into animalNames (id, name) values (64, 'Pheasant, common');
insert into animalNames (id, name) values (65, 'California sea lion');
insert into animalNames (id, name) values (66, 'Western pygmy possum');
insert into animalNames (id, name) values (67, 'Francolin, swainson''s');
insert into animalNames (id, name) values (68, 'Albatross, galapagos');
insert into animalNames (id, name) values (69, 'Great white pelican');
insert into animalNames (id, name) values (70, 'Grenadier, common');
insert into animalNames (id, name) values (71, 'Cape raven');
insert into animalNames (id, name) values (72, 'Sambar');
insert into animalNames (id, name) values (73, 'Little cormorant');
insert into animalNames (id, name) values (74, 'Ox, musk');
insert into animalNames (id, name) values (75, 'Monkey, rhesus');
insert into animalNames (id, name) values (76, 'Chipmunk, least');
insert into animalNames (id, name) values (77, 'Thrasher, curve-billed');
insert into animalNames (id, name) values (78, 'Mockingbird, galapagos');
insert into animalNames (id, name) values (79, 'Eastern fox squirrel');
insert into animalNames (id, name) values (80, 'Swallow-tail gull');
insert into animalNames (id, name) values (81, 'Hoffman''s sloth');
insert into animalNames (id, name) values (82, 'Long-finned pilot whale');
insert into animalNames (id, name) values (83, 'Camel, dromedary');
insert into animalNames (id, name) values (84, 'Otter, north american river');
insert into animalNames (id, name) values (85, 'Raccoon, crab-eating');
insert into animalNames (id, name) values (86, 'Azara''s zorro');
insert into animalNames (id, name) values (87, 'Wood pigeon');
insert into animalNames (id, name) values (88, 'Kite, black');
insert into animalNames (id, name) values (89, 'Fox, north american red');
insert into animalNames (id, name) values (90, 'Vulture, lappet-faced');
insert into animalNames (id, name) values (91, 'Nyala');
insert into animalNames (id, name) values (92, 'Butterfly (unidentified)');
insert into animalNames (id, name) values (93, 'Porcupine, prehensile-tailed');
insert into animalNames (id, name) values (94, 'Long-crested hawk eagle');
insert into animalNames (id, name) values (95, 'Egret, cattle');
insert into animalNames (id, name) values (96, 'California sea lion');
insert into animalNames (id, name) values (97, 'Macaque, japanese');
insert into animalNames (id, name) values (98, 'Eurasian beaver');
insert into animalNames (id, name) values (99, 'Grenadier, common');
insert into animalNames (id, name) values (100, 'Gambel''s quail');


create table members (
	id INT,
	name VARCHAR(50),
	company VARCHAR(50),
	department VARCHAR(50),
	title VARCHAR(50),
	suffix VARCHAR(50)
);
insert into members (id, name, company, department, title, suffix) values (1, 'Ailyn Lucey', 'Kertzmann Group', 'Accounting', 'Financial Advisor', null);
insert into members (id, name, company, department, title, suffix) values (2, 'Miltie Crackel', 'Nicolas-Nader', 'Research and Development', 'Marketing Assistant', 'Sr');
insert into members (id, name, company, department, title, suffix) values (3, 'Arda Brownlie', 'Medhurst Inc', 'Business Development', 'Financial Advisor', null);
insert into members (id, name, company, department, title, suffix) values (4, 'Portia Ennever', 'Predovic Inc', 'Accounting', 'Nurse Practicioner', null);
insert into members (id, name, company, department, title, suffix) values (5, 'Den Bennion', 'Wiegand, Murphy and Mayert', 'Legal', 'Structural Engineer', null);
insert into members (id, name, company, department, title, suffix) values (6, 'Tremain Vase', 'Hartmann, Schulist and Parker', 'Human Resources', 'Assistant Manager', null);
insert into members (id, name, company, department, title, suffix) values (7, 'Ricardo Tombling', 'Bednar LLC', 'Business Development', 'VP Quality Control', null);
insert into members (id, name, company, department, title, suffix) values (8, 'Manny Dingwall', 'Konopelski and Sons', 'Research and Development', 'Environmental Specialist', null);
insert into members (id, name, company, department, title, suffix) values (9, 'Jinny Nevinson', 'Tillman and Sons', 'Business Development', 'Analog Circuit Design manager', null);
insert into members (id, name, company, department, title, suffix) values (10, 'Bibbie Heinemann', 'Metz-Swaniawski', 'Legal', 'Product Engineer', null);
insert into members (id, name, company, department, title, suffix) values (11, 'Jena Holworth', 'Bahringer-Mertz', 'Support', 'Budget/Accounting Analyst III', 'Sr');
insert into members (id, name, company, department, title, suffix) values (12, 'Betty Marcone', 'Pollich, Fisher and Dickinson', 'Research and Development', 'Account Representative III', null);
insert into members (id, name, company, department, title, suffix) values (13, 'Elke Du Fray', 'Eichmann-Kemmer', 'Human Resources', 'Internal Auditor', null);
insert into members (id, name, company, department, title, suffix) values (14, 'Lindy MacCrackan', 'Boyle-Rempel', 'Legal', 'Paralegal', null);
insert into members (id, name, company, department, title, suffix) values (15, 'Christel Mattin', 'Larkin, Trantow and Hahn', 'Services', 'Graphic Designer', null);
insert into members (id, name, company, department, title, suffix) values (16, 'Nicola De Clairmont', 'O''Reilly, Bode and Bosco', 'Services', 'Biostatistician I', null);
insert into members (id, name, company, department, title, suffix) values (17, 'Barde Perico', 'Feil, Murphy and Mills', 'Product Management', 'Dental Hygienist', null);
insert into members (id, name, company, department, title, suffix) values (18, 'Consuela Pignon', 'Krajcik LLC', 'Marketing', 'Senior Sales Associate', 'III');
insert into members (id, name, company, department, title, suffix) values (19, 'Melisent Grzeskowski', 'Fay-Gislason', 'Services', 'Account Representative III', null);
insert into members (id, name, company, department, title, suffix) values (20, 'Joelynn Inkpin', 'Witting LLC', 'Legal', 'Assistant Media Planner', null);
insert into members (id, name, company, department, title, suffix) values (21, 'Roselin Mutton', 'Schinner LLC', 'Services', 'Engineer III', null);
insert into members (id, name, company, department, title, suffix) values (22, 'Renelle Jeens', 'Hills, Veum and Pfeffer', 'Accounting', 'Recruiter', null);
insert into members (id, name, company, department, title, suffix) values (23, 'Arie Sidry', 'McGlynn-Bruen', 'Services', 'Software Test Engineer II', null);
insert into members (id, name, company, department, title, suffix) values (24, 'Egan Heynel', 'Moen Group', 'Sales', 'General Manager', null);
insert into members (id, name, company, department, title, suffix) values (25, 'Annis Monelli', 'Stroman, Metz and Koss', 'Services', 'Legal Assistant', null);
insert into members (id, name, company, department, title, suffix) values (26, 'Cassie Pratton', 'Kreiger Group', 'Support', 'Recruiting Manager', null);
insert into members (id, name, company, department, title, suffix) values (27, 'Luca Amiable', 'Flatley and Sons', 'Legal', 'VP Quality Control', null);
insert into members (id, name, company, department, title, suffix) values (28, 'Heinrick Denziloe', 'Luettgen, Bayer and Bechtelar', 'Services', 'VP Product Management', null);
insert into members (id, name, company, department, title, suffix) values (29, 'Aretha Aldrick', 'Crooks, Terry and Franecki', 'Engineering', 'Automation Specialist I', null);
insert into members (id, name, company, department, title, suffix) values (30, 'Noby Noads', 'Schiller-Hettinger', 'Services', 'Software Consultant', null);
insert into members (id, name, company, department, title, suffix) values (31, 'Sheff Whoston', 'Abshire-Smith', 'Accounting', 'Pharmacist', null);
insert into members (id, name, company, department, title, suffix) values (32, 'Octavius Huster', 'Gleichner-Mitchell', 'Research and Development', 'Automation Specialist II', null);
insert into members (id, name, company, department, title, suffix) values (33, 'Lewiss Wrathmell', 'Hansen-Gislason', 'Legal', 'Physical Therapy Assistant', null);
insert into members (id, name, company, department, title, suffix) values (34, 'Jean Taplin', 'Braun, White and Thompson', 'Human Resources', 'Senior Quality Engineer', null);
insert into members (id, name, company, department, title, suffix) values (35, 'Barri MacPhail', 'Ward-Hagenes', 'Accounting', 'Developer II', null);
insert into members (id, name, company, department, title, suffix) values (36, 'Saunder Cattroll', 'Waters-Connelly', 'Marketing', 'Programmer Analyst I', null);
insert into members (id, name, company, department, title, suffix) values (37, 'Netty Do', 'Herman, Greenfelder and Sawayn', 'Legal', 'Account Representative I', null);
insert into members (id, name, company, department, title, suffix) values (38, 'Martynne Kleinert', 'Schaden Group', 'Legal', 'Assistant Manager', null);
insert into members (id, name, company, department, title, suffix) values (39, 'Nicolis Kasbye', 'Dooley and Sons', 'Sales', 'Marketing Assistant', null);
insert into members (id, name, company, department, title, suffix) values (40, 'Kippar Anglish', 'Bechtelar LLC', 'Support', 'Software Test Engineer II', null);
insert into members (id, name, company, department, title, suffix) values (41, 'Bartlet Ruddiforth', 'Quitzon LLC', 'Accounting', 'Human Resources Manager', null);
insert into members (id, name, company, department, title, suffix) values (42, 'Haily Guirard', 'Stracke, Block and Cruickshank', 'Support', 'Financial Analyst', null);
insert into members (id, name, company, department, title, suffix) values (43, 'Gunther Bome', 'Batz LLC', 'Human Resources', 'Recruiting Manager', null);
insert into members (id, name, company, department, title, suffix) values (44, 'Marissa Sauven', 'Sipes Inc', 'Sales', 'VP Marketing', null);
insert into members (id, name, company, department, title, suffix) values (45, 'Virge Hansman', 'Weber Group', 'Support', 'Database Administrator III', null);
insert into members (id, name, company, department, title, suffix) values (46, 'Alva Brill', 'Friesen-Abbott', 'Services', 'Associate Professor', null);
insert into members (id, name, company, department, title, suffix) values (47, 'Joe Stredwick', 'Ortiz Group', 'Sales', 'Analyst Programmer', null);
insert into members (id, name, company, department, title, suffix) values (48, 'Meggi Camell', 'Aufderhar, Jacobi and Hayes', 'Training', 'Junior Executive', null);
insert into members (id, name, company, department, title, suffix) values (49, 'Robby Calbaithe', 'Rohan, Schroeder and Rodriguez', 'Business Development', 'Statistician IV', null);
insert into members (id, name, company, department, title, suffix) values (50, 'Malena Sterzaker', 'Nienow-Hintz', 'Engineering', 'Developer III', null);
insert into members (id, name, company, department, title, suffix) values (51, 'Verine Roony', 'Ernser-Cartwright', 'Sales', 'Director of Sales', null);
insert into members (id, name, company, department, title, suffix) values (52, 'Giffard Surgey', 'Deckow-Leffler', 'Business Development', 'Cost Accountant', null);
insert into members (id, name, company, department, title, suffix) values (53, 'Kylen Midghall', 'Steuber-Graham', 'Sales', 'Payment Adjustment Coordinator', null);
insert into members (id, name, company, department, title, suffix) values (54, 'Stearne Al Hirsi', 'Schamberger-Heller', 'Business Development', 'Junior Executive', 'IV');
insert into members (id, name, company, department, title, suffix) values (55, 'Iseabal Weddeburn', 'Mohr, Green and Zboncak', 'Training', 'Internal Auditor', null);
insert into members (id, name, company, department, title, suffix) values (56, 'Roxanne Abramovic', 'Spinka LLC', 'Product Management', 'Dental Hygienist', null);
insert into members (id, name, company, department, title, suffix) values (57, 'Sollie Whiff', 'Konopelski-Howe', 'Training', 'Technical Writer', 'III');
insert into members (id, name, company, department, title, suffix) values (58, 'Priscella Jephcote', 'Padberg, Rowe and Mitchell', 'Support', 'Assistant Professor', null);
insert into members (id, name, company, department, title, suffix) values (59, 'Oren Lammertz', 'Stamm, Kuhic and Turcotte', 'Legal', 'Chemical Engineer', 'III');
insert into members (id, name, company, department, title, suffix) values (60, 'Kellie Minshaw', 'Cormier, Ullrich and Fisher', 'Sales', 'Mechanical Systems Engineer', null);
insert into members (id, name, company, department, title, suffix) values (61, 'Rodolfo Biles', 'Howe Inc', 'Engineering', 'Web Designer I', null);
insert into members (id, name, company, department, title, suffix) values (62, 'Joete Blackburne', 'Bosco-Koch', 'Business Development', 'Database Administrator I', null);
insert into members (id, name, company, department, title, suffix) values (63, 'Sibley Clouston', 'Klein Inc', 'Legal', 'Database Administrator IV', null);
insert into members (id, name, company, department, title, suffix) values (64, 'Danna Durward', 'Dare Inc', 'Business Development', 'Food Chemist', null);
insert into members (id, name, company, department, title, suffix) values (65, 'Cortney Koomar', 'West Group', 'Product Management', 'Administrative Officer', null);
insert into members (id, name, company, department, title, suffix) values (66, 'Antony Gallgher', 'Abbott and Sons', 'Marketing', 'VP Product Management', 'IV');
insert into members (id, name, company, department, title, suffix) values (67, 'Imogen Shilleto', 'McLaughlin, Zemlak and MacGyver', 'Research and Development', 'Biostatistician IV', null);
insert into members (id, name, company, department, title, suffix) values (68, 'Marvin Gomes', 'Bradtke and Sons', 'Services', 'Tax Accountant', null);
insert into members (id, name, company, department, title, suffix) values (69, 'Peirce Striker', 'Toy-Gorczany', 'Legal', 'Assistant Manager', 'Sr');
insert into members (id, name, company, department, title, suffix) values (70, 'Emeline Gronow', 'Batz-Rogahn', 'Engineering', 'Analyst Programmer', null);
insert into members (id, name, company, department, title, suffix) values (71, 'Ferrell Rodrigues', 'Durgan, Kshlerin and Rodriguez', 'Legal', 'Programmer Analyst I', null);
insert into members (id, name, company, department, title, suffix) values (72, 'Tanhya Twitching', 'Ratke, Watsica and Strosin', 'Support', 'Senior Sales Associate', null);
insert into members (id, name, company, department, title, suffix) values (73, 'Ange Torrie', 'Gaylord Inc', 'Sales', 'Administrative Assistant I', null);
insert into members (id, name, company, department, title, suffix) values (74, 'Athena Spyby', 'Klocko, Sawayn and Rath', 'Support', 'Safety Technician IV', null);
insert into members (id, name, company, department, title, suffix) values (75, 'Taddeusz Saggers', 'Dare Inc', 'Accounting', 'Account Executive', null);
insert into members (id, name, company, department, title, suffix) values (76, 'Elias Seawell', 'Waters LLC', 'Marketing', 'Design Engineer', null);
insert into members (id, name, company, department, title, suffix) values (77, 'Laurence Hardin', 'Schaefer-Jast', 'Accounting', 'Help Desk Technician', null);
insert into members (id, name, company, department, title, suffix) values (78, 'Shannon Anderer', 'Franecki-Reinger', 'Research and Development', 'Executive Secretary', null);
insert into members (id, name, company, department, title, suffix) values (79, 'Stuart Vela', 'Frami, Wolff and Botsford', 'Marketing', 'GIS Technical Architect', null);
insert into members (id, name, company, department, title, suffix) values (80, 'Kevin Revie', 'Dickens-Hickle', 'Support', 'VP Sales', null);
insert into members (id, name, company, department, title, suffix) values (81, 'Aura Titt', 'Boehm Group', 'Training', 'Geological Engineer', null);
insert into members (id, name, company, department, title, suffix) values (82, 'Evelyn Van Dalen', 'Grimes LLC', 'Sales', 'Recruiter', null);
insert into members (id, name, company, department, title, suffix) values (83, 'Herbert Vonasek', 'Labadie, Pollich and Greenfelder', 'Training', 'Human Resources Assistant IV', null);
insert into members (id, name, company, department, title, suffix) values (84, 'Lea Hughes', 'Cassin-Funk', 'Product Management', 'Electrical Engineer', null);
insert into members (id, name, company, department, title, suffix) values (85, 'Karlik Baddam', 'Goyette-O''Reilly', 'Services', 'Senior Editor', null);
insert into members (id, name, company, department, title, suffix) values (86, 'Janna Gillibrand', 'Howell LLC', 'Business Development', 'Account Coordinator', 'IV');
insert into members (id, name, company, department, title, suffix) values (87, 'Donnie Pentycross', 'Auer-Mitchell', 'Marketing', 'VP Product Management', null);
insert into members (id, name, company, department, title, suffix) values (88, 'Melany Neeve', 'Batz-Shanahan', 'Sales', 'Recruiting Manager', null);
insert into members (id, name, company, department, title, suffix) values (89, 'Lynsey Olivey', 'Runolfsdottir-Tillman', 'Product Management', 'Registered Nurse', null);
insert into members (id, name, company, department, title, suffix) values (90, 'Neely Montgomery', 'Leuschke-Marks', 'Business Development', 'VP Quality Control', null);
insert into members (id, name, company, department, title, suffix) values (91, 'Justin Thorp', 'Mills-Borer', 'Accounting', 'Nuclear Power Engineer', null);
insert into members (id, name, company, department, title, suffix) values (92, 'Augustine Kempston', 'Kemmer and Sons', 'Support', 'Developer II', null);
insert into members (id, name, company, department, title, suffix) values (93, 'Daria Dei', 'Grimes, Schumm and Bashirian', 'Research and Development', 'Teacher', null);
insert into members (id, name, company, department, title, suffix) values (94, 'Sarina Sange', 'Mertz-Lehner', 'Training', 'Teacher', null);
insert into members (id, name, company, department, title, suffix) values (95, 'Annetta Yard', 'Cole, Emmerich and Ebert', 'Marketing', 'Occupational Therapist', null);
insert into members (id, name, company, department, title, suffix) values (96, 'Meir Hepher', 'Eichmann-Murazik', 'Human Resources', 'Tax Accountant', null);
insert into members (id, name, company, department, title, suffix) values (97, 'Alie Lewcock', 'Hermiston-Grimes', 'Legal', 'Safety Technician IV', null);
insert into members (id, name, company, department, title, suffix) values (98, 'Fidel Faherty', 'Lang-Gerlach', 'Training', 'Community Outreach Specialist', null);
insert into members (id, name, company, department, title, suffix) values (99, 'Christyna Gange', 'Kuhlman, Kling and Crist', 'Accounting', 'Teacher', null);
insert into members (id, name, company, department, title, suffix) values (100, 'Dennis Pomfrey', 'Larson-Brakus', 'Services', 'Community Outreach Specialist', null);


create table test (
	id INT,
	username VARCHAR(50),
	info_updated DATETIME
);
insert into test (id, username, info_updated) values (1, 'alinebarger0', '2020-04-12 13:00:39');
insert into test (id, username, info_updated) values (2, 'jmoffett1', '2020-09-30 10:14:30');
insert into test (id, username, info_updated) values (3, 'cbixley2', '2020-04-06 17:29:18');
insert into test (id, username, info_updated) values (4, 'nyushachkov3', '2020-05-25 15:14:50');
insert into test (id, username, info_updated) values (5, 'haudiss4', '2020-05-27 00:11:27');
insert into test (id, username, info_updated) values (6, 'kcornejo5', '2020-05-17 18:13:36');
insert into test (id, username, info_updated) values (7, 'ahowden6', '2020-11-02 22:03:13');
insert into test (id, username, info_updated) values (8, 'mmattevi7', '2020-12-10 01:57:44');
insert into test (id, username, info_updated) values (9, 'wneagle8', '2021-02-08 01:46:01');
insert into test (id, username, info_updated) values (10, 'agiacomazzo9', '2020-03-25 18:21:20');
insert into test (id, username, info_updated) values (11, 'rcalderheada', '2020-09-16 17:55:42');
insert into test (id, username, info_updated) values (12, 'jsyddieb', '2021-01-05 02:42:49');
insert into test (id, username, info_updated) values (13, 'ccalfc', '2020-03-24 05:16:28');
insert into test (id, username, info_updated) values (14, 'yfippd', '2020-07-01 10:41:23');
insert into test (id, username, info_updated) values (15, 'bwaytee', '2020-08-02 06:46:18');
insert into test (id, username, info_updated) values (16, 'ocermanf', '2020-10-02 17:45:26');
insert into test (id, username, info_updated) values (17, 'doshaughnessyg', '2020-06-21 21:12:19');
insert into test (id, username, info_updated) values (18, 'thaversonh', '2020-06-02 07:02:09');
insert into test (id, username, info_updated) values (19, 'cnisardi', '2020-05-20 14:21:42');
insert into test (id, username, info_updated) values (20, 'sspittlesj', '2020-08-29 16:26:27');
insert into test (id, username, info_updated) values (21, 'ariplyk', '2020-05-16 11:54:54');
insert into test (id, username, info_updated) values (22, 'vphippenl', '2020-04-30 03:21:38');
insert into test (id, username, info_updated) values (23, 'ktitmusm', '2020-05-24 08:51:46');
insert into test (id, username, info_updated) values (24, 'mburgissn', '2021-01-08 05:40:25');
insert into test (id, username, info_updated) values (25, 'dcasaccioo', '2020-04-08 21:40:06');
insert into test (id, username, info_updated) values (26, 'srosinip', '2020-06-08 01:41:14');
insert into test (id, username, info_updated) values (27, 'achastonq', '2020-07-13 02:46:03');
insert into test (id, username, info_updated) values (28, 'mmathivetr', '2020-04-23 07:19:20');
insert into test (id, username, info_updated) values (29, 'lfirles', '2020-07-26 09:41:04');
insert into test (id, username, info_updated) values (30, 'kfairmant', '2021-01-30 01:03:22');
insert into test (id, username, info_updated) values (31, 'utesoeu', '2020-05-25 01:02:23');
insert into test (id, username, info_updated) values (32, 'maspyv', '2020-10-04 02:28:36');
insert into test (id, username, info_updated) values (33, 'kgarberw', '2021-01-26 19:31:09');
insert into test (id, username, info_updated) values (34, 'ctollettx', '2020-08-09 09:40:47');
insert into test (id, username, info_updated) values (35, 'locanavany', '2020-09-24 04:32:26');
insert into test (id, username, info_updated) values (36, 'lsidesz', '2021-01-29 10:35:43');
insert into test (id, username, info_updated) values (37, 'abernon10', '2020-07-06 13:29:50');
insert into test (id, username, info_updated) values (38, 'dmotherwell11', '2020-04-19 00:17:38');
insert into test (id, username, info_updated) values (39, 'rneesam12', '2020-09-19 11:24:18');
insert into test (id, username, info_updated) values (40, 'kbryden13', '2021-01-01 01:10:12');
insert into test (id, username, info_updated) values (41, 'mforsbey14', '2020-10-24 21:23:47');
insert into test (id, username, info_updated) values (42, 'pmcfadyen15', '2020-10-22 00:19:06');
insert into test (id, username, info_updated) values (43, 'lyuryichev16', '2020-10-29 05:31:29');
insert into test (id, username, info_updated) values (44, 'nstreight17', '2020-09-27 11:11:07');
insert into test (id, username, info_updated) values (45, 'mcrohan18', '2020-10-26 09:50:50');
insert into test (id, username, info_updated) values (46, 'mcorah19', '2020-03-31 09:49:55');
insert into test (id, username, info_updated) values (47, 'sjendrys1a', '2020-06-24 00:45:25');
insert into test (id, username, info_updated) values (48, 'edoward1b', '2020-11-08 05:55:27');
insert into test (id, username, info_updated) values (49, 'isouttar1c', '2020-11-18 22:22:51');
insert into test (id, username, info_updated) values (50, 'croman1d', '2021-02-09 15:30:23');
insert into test (id, username, info_updated) values (51, 'yraccio1e', '2020-03-22 20:06:17');
insert into test (id, username, info_updated) values (52, 'ggreenlees1f', '2020-03-27 04:44:58');
insert into test (id, username, info_updated) values (53, 'nhebden1g', '2020-09-09 05:21:40');
insert into test (id, username, info_updated) values (54, 'egossage1h', '2020-12-30 15:34:04');
insert into test (id, username, info_updated) values (55, 'smaccaig1i', '2020-09-19 15:11:38');
insert into test (id, username, info_updated) values (56, 'hmillam1j', '2020-10-16 02:04:19');
insert into test (id, username, info_updated) values (57, 'lknok1k', '2020-07-29 16:00:10');
insert into test (id, username, info_updated) values (58, 'kspykins1l', '2020-06-14 21:58:51');
insert into test (id, username, info_updated) values (59, 'qbrecon1m', '2020-08-24 23:04:56');
insert into test (id, username, info_updated) values (60, 'jpaoli1n', '2020-11-18 02:20:25');
insert into test (id, username, info_updated) values (61, 'mkrolak1o', '2021-02-28 10:35:02');
insert into test (id, username, info_updated) values (62, 'gheavy1p', '2021-01-31 17:24:09');
insert into test (id, username, info_updated) values (63, 'jjellyman1q', '2020-03-29 12:56:12');
insert into test (id, username, info_updated) values (64, 'fstorkes1r', '2021-02-13 04:02:26');
insert into test (id, username, info_updated) values (65, 'sfellibrand1s', '2020-05-31 22:41:47');
insert into test (id, username, info_updated) values (66, 'djoutapavicius1t', '2020-05-08 12:11:57');
insert into test (id, username, info_updated) values (67, 'dstening1u', '2020-03-21 17:12:30');
insert into test (id, username, info_updated) values (68, 'rdallicoat1v', '2021-02-09 03:14:19');
insert into test (id, username, info_updated) values (69, 'etyrrell1w', '2020-04-03 04:50:10');
insert into test (id, username, info_updated) values (70, 'mdeavenell1x', '2020-04-01 06:13:20');
insert into test (id, username, info_updated) values (71, 'btutton1y', '2020-12-11 17:22:59');
insert into test (id, username, info_updated) values (72, 'abateup1z', '2020-03-28 01:39:25');
insert into test (id, username, info_updated) values (73, 'kjeakins20', '2020-12-18 01:36:57');
insert into test (id, username, info_updated) values (74, 'rpostin21', '2020-04-29 03:41:46');
insert into test (id, username, info_updated) values (75, 'tgosnay22', '2020-12-12 22:56:24');
insert into test (id, username, info_updated) values (76, 'fmurty23', '2021-02-25 02:19:00');
insert into test (id, username, info_updated) values (77, 'mworg24', '2020-07-14 11:22:27');
insert into test (id, username, info_updated) values (78, 'zcharlick25', '2020-07-09 11:00:04');
insert into test (id, username, info_updated) values (79, 'lmacallam26', '2020-11-28 23:44:28');
insert into test (id, username, info_updated) values (80, 'mpoundesford27', '2020-06-29 08:27:48');
insert into test (id, username, info_updated) values (81, 'ccausley28', '2020-10-08 06:12:08');
insert into test (id, username, info_updated) values (82, 'ahamner29', '2021-02-25 15:40:36');
insert into test (id, username, info_updated) values (83, 'felby2a', '2020-10-08 02:00:47');
insert into test (id, username, info_updated) values (84, 'mrankling2b', '2020-07-07 02:50:45');
insert into test (id, username, info_updated) values (85, 'mjaques2c', '2020-05-30 21:04:21');
insert into test (id, username, info_updated) values (86, 'awinmill2d', '2020-09-27 18:54:26');
insert into test (id, username, info_updated) values (87, 'smatuszinski2e', '2020-10-10 05:21:14');
insert into test (id, username, info_updated) values (88, 'ahammond2f', '2021-02-28 04:30:45');
insert into test (id, username, info_updated) values (89, 'ctasseler2g', '2020-03-11 21:43:00');
insert into test (id, username, info_updated) values (90, 'ihue2h', '2021-02-19 08:44:59');
insert into test (id, username, info_updated) values (91, 'fadacot2i', '2020-12-13 13:31:50');
insert into test (id, username, info_updated) values (92, 'rpenning2j', '2020-10-28 19:29:29');
insert into test (id, username, info_updated) values (93, 'tgleeson2k', '2020-05-02 17:32:52');
insert into test (id, username, info_updated) values (94, 'akenworthy2l', '2020-08-16 16:46:22');
insert into test (id, username, info_updated) values (95, 'nkingsnode2m', '2021-01-13 22:35:49');
insert into test (id, username, info_updated) values (96, 'kmcilwrick2n', '2020-06-21 06:58:26');
insert into test (id, username, info_updated) values (97, 'epirnie2o', '2020-05-08 01:43:46');
insert into test (id, username, info_updated) values (98, 'mshoebotham2p', '2020-06-13 18:20:48');
insert into test (id, username, info_updated) values (99, 'dbeech2q', '2020-03-11 06:41:11');
insert into test (id, username, info_updated) values (100, 'rbuckler2r', '2020-11-13 10:52:34');


create table customerData (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(50)
);
insert into customerData (id, first_name, last_name, email, gender) values (1, 'Charissa', 'Westmoreland', 'cwestmoreland0@mozilla.org', 'Genderqueer');
insert into customerData (id, first_name, last_name, email, gender) values (2, 'Yankee', 'Goodson', 'ygoodson1@nationalgeographic.com', 'Polygender');
insert into customerData (id, first_name, last_name, email, gender) values (3, 'Georgia', 'Munkley', 'gmunkley2@yahoo.com', 'Bigender');
insert into customerData (id, first_name, last_name, email, gender) values (4, 'Karissa', 'Demelt', 'kdemelt3@bbb.org', 'Male');
insert into customerData (id, first_name, last_name, email, gender) values (5, 'Cece', 'Benitez', 'cbenitez4@yahoo.com', 'Non-binary');
insert into customerData (id, first_name, last_name, email, gender) values (6, 'Harriette', 'Koba', 'hkoba5@behance.net', 'Male');
insert into customerData (id, first_name, last_name, email, gender) values (7, 'Winnie', 'Newport', 'wnewport6@yolasite.com', 'Male');
insert into customerData (id, first_name, last_name, email, gender) values (8, 'Germana', 'Spring', 'gspring7@vistaprint.com', 'Male');
insert into customerData (id, first_name, last_name, email, gender) values (9, 'Lindsay', 'Seeger', 'lseeger8@vkontakte.ru', 'Polygender');
insert into customerData (id, first_name, last_name, email, gender) values (10, 'King', 'Gillbee', 'kgillbee9@ted.com', 'Genderqueer');
insert into customerData (id, first_name, last_name, email, gender) values (11, 'Sol', 'Btham', 'sbthama@xinhuanet.com', 'Agender');
insert into customerData (id, first_name, last_name, email, gender) values (12, 'Stephan', 'Mattheis', 'smattheisb@clickbank.net', 'Bigender');
insert into customerData (id, first_name, last_name, email, gender) values (13, 'Rees', 'Quidenham', 'rquidenhamc@aol.com', 'Male');
insert into customerData (id, first_name, last_name, email, gender) values (14, 'Pamella', 'Bodiam', 'pbodiamd@springer.com', 'Polygender');
insert into customerData (id, first_name, last_name, email, gender) values (15, 'Katti', 'Shimman', 'kshimmane@slashdot.org', 'Bigender');
insert into customerData (id, first_name, last_name, email, gender) values (16, 'Marwin', 'Tyer', 'mtyerf@apple.com', 'Female');
insert into customerData (id, first_name, last_name, email, gender) values (17, 'Pearla', 'Dufaur', 'pdufaurg@studiopress.com', 'Genderfluid');
insert into customerData (id, first_name, last_name, email, gender) values (18, 'Deb', 'Pappi', 'dpappih@taobao.com', 'Genderfluid');
insert into customerData (id, first_name, last_name, email, gender) values (19, 'Yankee', 'Pfertner', 'ypfertneri@weebly.com', 'Polygender');
insert into customerData (id, first_name, last_name, email, gender) values (20, 'Corey', 'Mowne', 'cmownej@netlog.com', 'Male');
insert into customerData (id, first_name, last_name, email, gender) values (21, 'Stanfield', 'Havock', 'shavockk@webs.com', 'Non-binary');
insert into customerData (id, first_name, last_name, email, gender) values (22, 'Lockwood', 'Lodeke', 'llodekel@hubpages.com', 'Agender');
insert into customerData (id, first_name, last_name, email, gender) values (23, 'Maiga', 'Bidnall', 'mbidnallm@last.fm', 'Male');
insert into customerData (id, first_name, last_name, email, gender) values (24, 'Germaine', 'Arnoldi', 'garnoldin@shop-pro.jp', 'Female');
insert into customerData (id, first_name, last_name, email, gender) values (25, 'Herculie', 'Stenett', 'hstenetto@hostgator.com', 'Polygender');
insert into customerData (id, first_name, last_name, email, gender) values (26, 'Olvan', 'Speller', 'ospellerp@amazon.de', 'Genderqueer');
insert into customerData (id, first_name, last_name, email, gender) values (27, 'Isahella', 'Close', 'icloseq@blog.com', 'Non-binary');
insert into customerData (id, first_name, last_name, email, gender) values (28, 'Benedicta', 'Vinas', 'bvinasr@tuttocitta.it', 'Polygender');
insert into customerData (id, first_name, last_name, email, gender) values (29, 'Alfreda', 'Keal', 'akeals@bloglines.com', 'Male');
insert into customerData (id, first_name, last_name, email, gender) values (30, 'Town', 'Eckh', 'teckht@vimeo.com', 'Bigender');
insert into customerData (id, first_name, last_name, email, gender) values (31, 'Anallise', 'Barnard', 'abarnardu@naver.com', 'Female');
insert into customerData (id, first_name, last_name, email, gender) values (32, 'Erroll', 'Dearman', 'edearmanv@hibu.com', 'Bigender');
insert into customerData (id, first_name, last_name, email, gender) values (33, 'Eb', 'Perrett', 'eperrettw@bizjournals.com', 'Female');
insert into customerData (id, first_name, last_name, email, gender) values (34, 'Diannne', 'Boulden', 'dbouldenx@dion.ne.jp', 'Male');
insert into customerData (id, first_name, last_name, email, gender) values (35, 'Trip', 'Venn', 'tvenny@flickr.com', 'Polygender');
insert into customerData (id, first_name, last_name, email, gender) values (36, 'Vivianne', 'Teresse', 'vteressez@bbb.org', 'Genderfluid');
insert into customerData (id, first_name, last_name, email, gender) values (37, 'Saundra', 'Saur', 'ssaur10@shinystat.com', 'Genderqueer');
insert into customerData (id, first_name, last_name, email, gender) values (38, 'Prisca', 'Hovenden', 'phovenden11@umn.edu', 'Agender');
insert into customerData (id, first_name, last_name, email, gender) values (39, 'Mary', 'Lumby', 'mlumby12@barnesandnoble.com', 'Agender');
insert into customerData (id, first_name, last_name, email, gender) values (40, 'Ansel', 'Koschek', 'akoschek13@elpais.com', 'Bigender');
insert into customerData (id, first_name, last_name, email, gender) values (41, 'Ely', 'Dyerson', 'edyerson14@privacy.gov.au', 'Agender');
insert into customerData (id, first_name, last_name, email, gender) values (42, 'Genny', 'Seedhouse', 'gseedhouse15@redcross.org', 'Genderqueer');
insert into customerData (id, first_name, last_name, email, gender) values (43, 'Rochette', 'Slimings', 'rslimings16@studiopress.com', 'Genderfluid');
insert into customerData (id, first_name, last_name, email, gender) values (44, 'Janeen', 'Andrusov', 'jandrusov17@theguardian.com', 'Male');
insert into customerData (id, first_name, last_name, email, gender) values (45, 'Jackie', 'Pettit', 'jpettit18@google.com.br', 'Genderfluid');
insert into customerData (id, first_name, last_name, email, gender) values (46, 'Chic', 'Charpin', 'ccharpin19@ebay.com', 'Female');
insert into customerData (id, first_name, last_name, email, gender) values (47, 'Jasun', 'Lamburn', 'jlamburn1a@smugmug.com', 'Bigender');
insert into customerData (id, first_name, last_name, email, gender) values (48, 'Gael', 'Adamides', 'gadamides1b@homestead.com', 'Male');
insert into customerData (id, first_name, last_name, email, gender) values (49, 'Elberta', 'Paulson', 'epaulson1c@biblegateway.com', 'Non-binary');
insert into customerData (id, first_name, last_name, email, gender) values (50, 'Wilden', 'Sagerson', 'wsagerson1d@whitehouse.gov', 'Female');
insert into customerData (id, first_name, last_name, email, gender) values (51, 'Gunner', 'Crosland', 'gcrosland1e@ameblo.jp', 'Non-binary');
insert into customerData (id, first_name, last_name, email, gender) values (52, 'Joshua', 'Blackwell', 'jblackwell1f@ask.com', 'Agender');
insert into customerData (id, first_name, last_name, email, gender) values (53, 'Tallia', 'McGaughey', 'tmcgaughey1g@fotki.com', 'Polygender');
insert into customerData (id, first_name, last_name, email, gender) values (54, 'Perceval', 'Klimkiewich', 'pklimkiewich1h@patch.com', 'Polygender');
insert into customerData (id, first_name, last_name, email, gender) values (55, 'Eustacia', 'Hugh', 'ehugh1i@ustream.tv', 'Genderfluid');
insert into customerData (id, first_name, last_name, email, gender) values (56, 'Nate', 'Lowman', 'nlowman1j@umich.edu', 'Polygender');
insert into customerData (id, first_name, last_name, email, gender) values (57, 'Henriette', 'Brunetti', 'hbrunetti1k@infoseek.co.jp', 'Agender');
insert into customerData (id, first_name, last_name, email, gender) values (58, 'Cathy', 'Spriggs', 'cspriggs1l@chron.com', 'Bigender');
insert into customerData (id, first_name, last_name, email, gender) values (59, 'Valaria', 'Beton', 'vbeton1m@prweb.com', 'Agender');
insert into customerData (id, first_name, last_name, email, gender) values (60, 'Darrell', 'Lilburne', 'dlilburne1n@dagondesign.com', 'Bigender');
insert into customerData (id, first_name, last_name, email, gender) values (61, 'Lorry', 'Ianetti', 'lianetti1o@nytimes.com', 'Female');
insert into customerData (id, first_name, last_name, email, gender) values (62, 'Loralie', 'Burberry', 'lburberry1p@whitehouse.gov', 'Agender');
insert into customerData (id, first_name, last_name, email, gender) values (63, 'Catriona', 'McIlroy', 'cmcilroy1q@squarespace.com', 'Non-binary');
insert into customerData (id, first_name, last_name, email, gender) values (64, 'Tabbie', 'Wrathall', 'twrathall1r@ning.com', 'Bigender');
insert into customerData (id, first_name, last_name, email, gender) values (65, 'Sanford', 'Lidgard', 'slidgard1s@stanford.edu', 'Non-binary');
insert into customerData (id, first_name, last_name, email, gender) values (66, 'Sybilla', 'Oneill', 'soneill1t@networkadvertising.org', 'Non-binary');
insert into customerData (id, first_name, last_name, email, gender) values (67, 'Adair', 'Bestall', 'abestall1u@networkadvertising.org', 'Non-binary');
insert into customerData (id, first_name, last_name, email, gender) values (68, 'Marisa', 'Stanyer', 'mstanyer1v@shareasale.com', 'Genderqueer');
insert into customerData (id, first_name, last_name, email, gender) values (69, 'Alejoa', 'Edensor', 'aedensor1w@topsy.com', 'Agender');
insert into customerData (id, first_name, last_name, email, gender) values (70, 'Alix', 'Gibbieson', 'agibbieson1x@pcworld.com', 'Agender');
insert into customerData (id, first_name, last_name, email, gender) values (71, 'Menard', 'Poynser', 'mpoynser1y@smugmug.com', 'Genderqueer');
insert into customerData (id, first_name, last_name, email, gender) values (72, 'Angelico', 'Gethen', 'agethen1z@ameblo.jp', 'Bigender');
insert into customerData (id, first_name, last_name, email, gender) values (73, 'Pincus', 'Cutbirth', 'pcutbirth20@bbb.org', 'Genderqueer');
insert into customerData (id, first_name, last_name, email, gender) values (74, 'Marnie', 'Arrell', 'marrell21@163.com', 'Genderqueer');
insert into customerData (id, first_name, last_name, email, gender) values (75, 'Annabella', 'Graffham', 'agraffham22@wufoo.com', 'Male');
insert into customerData (id, first_name, last_name, email, gender) values (76, 'Tedd', 'Lamacraft', 'tlamacraft23@opera.com', 'Male');
insert into customerData (id, first_name, last_name, email, gender) values (77, 'Gisella', 'McGray', 'gmcgray24@studiopress.com', 'Genderqueer');
insert into customerData (id, first_name, last_name, email, gender) values (78, 'Horatia', 'Kordovani', 'hkordovani25@sohu.com', 'Non-binary');
insert into customerData (id, first_name, last_name, email, gender) values (79, 'Nertie', 'Yerson', 'nyerson26@qq.com', 'Polygender');
insert into customerData (id, first_name, last_name, email, gender) values (80, 'Deane', 'Olexa', 'dolexa27@cam.ac.uk', 'Non-binary');
insert into customerData (id, first_name, last_name, email, gender) values (81, 'Lauralee', 'Claxson', 'lclaxson28@skype.com', 'Male');
insert into customerData (id, first_name, last_name, email, gender) values (82, 'Sumner', 'Wilks', 'swilks29@epa.gov', 'Female');
insert into customerData (id, first_name, last_name, email, gender) values (83, 'Natale', 'Tale', 'ntale2a@dell.com', 'Agender');
insert into customerData (id, first_name, last_name, email, gender) values (84, 'Kass', 'Seal', 'kseal2b@paypal.com', 'Genderfluid');
insert into customerData (id, first_name, last_name, email, gender) values (85, 'Bjorn', 'Konzelmann', 'bkonzelmann2c@xing.com', 'Polygender');
insert into customerData (id, first_name, last_name, email, gender) values (86, 'Georgeta', 'Tinsley', 'gtinsley2d@archive.org', 'Bigender');
insert into customerData (id, first_name, last_name, email, gender) values (87, 'Raynell', 'Margetson', 'rmargetson2e@google.co.uk', 'Male');
insert into customerData (id, first_name, last_name, email, gender) values (88, 'Fawnia', 'Baiden', 'fbaiden2f@ted.com', 'Non-binary');
insert into customerData (id, first_name, last_name, email, gender) values (89, 'Hallie', 'Covelle', 'hcovelle2g@constantcontact.com', 'Genderfluid');
insert into customerData (id, first_name, last_name, email, gender) values (90, 'Obadiah', 'Habbin', 'ohabbin2h@alibaba.com', 'Polygender');
insert into customerData (id, first_name, last_name, email, gender) values (91, 'Kele', 'Denison', 'kdenison2i@princeton.edu', 'Genderqueer');
insert into customerData (id, first_name, last_name, email, gender) values (92, 'Moss', 'Daventry', 'mdaventry2j@patch.com', 'Male');
insert into customerData (id, first_name, last_name, email, gender) values (93, 'Chariot', 'Cricket', 'ccricket2k@about.com', 'Genderfluid');
insert into customerData (id, first_name, last_name, email, gender) values (94, 'Marketa', 'Woolatt', 'mwoolatt2l@chron.com', 'Male');
insert into customerData (id, first_name, last_name, email, gender) values (95, 'Marketa', 'Seares', 'mseares2m@over-blog.com', 'Non-binary');
insert into customerData (id, first_name, last_name, email, gender) values (96, 'Gaylord', 'Luffman', 'gluffman2n@smh.com.au', 'Female');
insert into customerData (id, first_name, last_name, email, gender) values (97, 'Donavon', 'Benwell', 'dbenwell2o@mapy.cz', 'Non-binary');
insert into customerData (id, first_name, last_name, email, gender) values (98, 'Alysa', 'Coaten', 'acoaten2p@chron.com', 'Bigender');
insert into customerData (id, first_name, last_name, email, gender) values (99, 'Dominick', 'Whickman', 'dwhickman2q@fotki.com', 'Female');
insert into customerData (id, first_name, last_name, email, gender) values (100, 'Lamar', 'Glauber', 'lglauber2r@ning.com', 'Polygender');


create table groceries (
	id INT,
	grocery VARCHAR(50),
	vendor VARCHAR(50),
	qty INT,
	buy_price DECIMAL(4,2),
	sell_price DECIMAL(4,2)
);
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (1, 'Rice - Brown', 'Abshire and Sons', 395, 16.36, '17.47');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (2, 'Pepper - Cayenne', 'Kemmer, Lakin and Huels', 1, 5.51, '5.86');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (3, 'Cake Circle, Foil, Scallop', 'Huels, Lehner and Purdy', 398, 7.24, '7.82');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (4, 'Lychee', 'Kilback Group', 685, 4.89, '5.17');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (5, 'Remy Red Berry Infusion', 'Smith LLC', 373, 4.59, '4.99');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (6, 'Beef - Bones, Cut - Up', 'Jenkins-Renner', 276, 9.26, '10.05');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (7, 'Garbag Bags - Black', 'Abernathy Group', 252, 8.12, '8.89');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (8, 'Chicken Breast Halal', 'Hauck Inc', 562, 1.11, '1.22');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (9, 'Cheese - Romano, Grated', 'Davis Inc', 260, 18.49, '19.74');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (10, 'Flour - Rye', 'Mayert-Dicki', 448, 13.43, '14.72');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (11, 'Sesame Seed', 'D''Amore, Kling and Prosacco', 593, 16.58, '17.61');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (12, 'Trueblue - Blueberry', 'Harvey, Kshlerin and Dickinson', 827, 19.6, '21.45');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (13, 'Carbonated Water - Strawberry', 'McGlynn, Macejkovic and Russel', 934, 15.19, '16.02');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (14, 'Madeira', 'Gottlieb-Hilpert', 556, 5.0, '5.47');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (15, 'Eggplant Oriental', 'Yost Inc', 211, 3.33, '3.61');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (16, 'Water - Spring Water, 355 Ml', 'Borer-O''Reilly', 607, 13.16, '14.35');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (17, 'Gatorade - Orange', 'Roob-Boyer', 31, 5.25, '5.52');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (18, 'Cabbage - Red', 'Howell, Altenwerth and Kerluke', 803, 1.16, '1.24');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (19, 'Table Cloth 120 Round White', 'Johnson-Monahan', 131, 12.26, '13.07');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (20, 'Island Oasis - Ice Cream Mix', 'Tillman Group', 334, 8.22, '8.67');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (21, 'Fond - Neutral', 'Lueilwitz LLC', 296, 2.67, '2.83');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (22, 'Glass Clear 7 Oz Xl', 'Brekke LLC', 303, 6.81, '7.31');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (23, 'Swordfish Loin Portions', 'Deckow and Sons', 264, 16.53, '18.16');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (24, 'Cocoa Powder - Natural', 'Erdman Inc', 762, 14.93, '16.36');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (25, 'Seabream Whole Farmed', 'Hayes Inc', 313, 2.13, '2.27');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (26, 'Tomatoes - Grape', 'Flatley, Ortiz and Witting', 275, 5.95, '6.41');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (27, 'Soup - Campbells Mushroom', 'Heathcote and Sons', 575, 15.41, '16.45');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (28, 'Wine - White, Pelee Island', 'Harvey, Kertzmann and Kertzmann', 80, 12.55, '13.53');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (29, 'Bar Bran Honey Nut', 'Beatty LLC', 931, 1.68, '1.79');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (30, 'Potatoes - Instant, Mashed', 'Hettinger, Ritchie and West', 507, 5.96, '6.46');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (31, 'Compound - Passion Fruit', 'Turner LLC', 5, 16.22, '17.43');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (32, 'Loquat', 'Runte Inc', 260, 2.66, '2.91');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (33, 'Pickerel - Fillets', 'Wintheiser and Sons', 645, 17.21, '18.42');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (34, 'Potatoes - Yukon Gold, 80 Ct', 'Hackett and Sons', 727, 13.24, '14.33');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (35, 'Pears - Bartlett', 'Oberbrunner Group', 44, 5.67, '6.23');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (36, 'Barley - Pearl', 'McDermott Group', 111, 5.95, '6.33');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (37, 'Monkfish Fresh - Skin Off', 'Kovacek, Brekke and Zboncak', 371, 5.65, '6.05');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (38, 'Cookies - Fortune', 'O''Reilly Inc', 392, 17.22, '18.24');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (39, 'Apricots - Halves', 'Morissette, Braun and Parker', 300, 2.79, '3.02');
insert into groceries (id, grocery, vendor, qty, buy_price, sell_price) values (40, 'Currants', 'Cartwright Inc', 562, 8.93, '9.63');